version: '3.4'

services:
  labequip:
    networks:
      - nginx_default
    container_name: labequip
    image: labequip
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - dist:/labEquip
    restart: always
    ports:
      - 90:80
volumes:
  dist:
networks:
  nginx_default:
    external: true
