version: '3.4'

services:
  labequip:
    container_name: labequip
    image: labequip
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./dist:/labEquip
    restart: always
    ports:
      - '8080:8080'
volumes:
  data:
